dist: trusty
sudo: require
language: cpp
compiler: gcc
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-6
      - g++-6
      - cmake
      - git
script:
  - sudo ln -s /usr/bin/gcc-6 /usr/local/bin/gcc
  - sudo ln -s /usr/bin/g++-6 /usr/local/bin/g++
  - git clone https://github.com/jbeder/yaml-cpp ../yaml
  - cd ../yaml
  - mkdir build
  - cd build
  - cmake ..
  - sudo cmake --build . -- -j4 install
  - cd ../malt_core
  - git clone https://github.com/malt3d/malt_cmake ../malt_cmake
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build . -- -j4